const products = [
  {
    name: "9K Gold Classic Necklace",
    price: 32000,
    category: "necklace",
    description: "Elegant 9k gold necklace with minimal classic design.",
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=600&auto=format&fit=crop",
    rating: 4.6,
    stock: 0,
    material: "9K Yellow Gold",
    weight: "4.5g",
    purity: "37.5% Gold",
    dimensions: "45cm Chain",
    gemstone: "None",
    metalFinish: "Polished",
    warranty: "1 Year"
  },
  {
    name: "Silver Pearl Necklace Set",
    price: 18000,
    category: "necklace",
    description: "Beautiful silver necklace paired with pearl beads.",
    image: "https://images.pexels.com/photos/33370257/pexels-photo-33370257.jpeg",
    rating: 4.5,
    stock: 1,
    material: "Sterling Silver",
    weight: "5.8g",
    purity: "92.5% Silver",
    dimensions: "40cm + 5cm adjustment",
    gemstone: "Freshwater Pearl",
    metalFinish: "Rhodium Plated",
    warranty: "6 Months"
  },
  {
    name: "9K Gold Layer Necklace",
    price: 45000,
    category: "necklace",
    description: "Traditional bridal necklace made with 9k gold.",
    image: "https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=700&auto=format&fit=crop",
    rating: 4.8,
    stock: 16,
    material: "9K Yellow Gold",
    weight: "14.2g",
    purity: "37.5% Gold",
    dimensions: "50cm Drop Design",
    gemstone: "Cubic Zirconia",
    metalFinish: "High Shine",
    warranty: "2 Years"
  },
  {
    name: "9K Gold Modern Necklace",
    price: 35000,
    category: "necklace",
    description: "Modern pattern necklace crafted in 9k gold.",
    image: "https://watchdirect.com.au/cdn/shop/files/9YN0428.jpg?v=1761014330&width=2048",
    rating: 4.7,
    stock: 17,
    material: "9K Rose Gold",
    weight: "6.5g",
    purity: "37.5% Gold",
    dimensions: "42cm",
    gemstone: "None",
    metalFinish: "Matte/Satin Finish",
    warranty: "1 Year"
  },

  {
    name: "9K Gold Stud Earrings",
    price: 12000,
    category: "earrings",
    description: "Simple and elegant 9k gold stud earrings.",
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=600&auto=format&fit=crop",
    rating: 4.4,
    stock: 15,
    material: "9K Yellow Gold",
    weight: "1.1g",
    purity: "37.5% Gold",
    dimensions: "6mm Diameter",
    gemstone: "None",
    metalFinish: "Polished",
    warranty: "1 Year"
  },
  {
    name: "Silver Hoop Earrings",
    price: 9000,
    category: "earrings",
    description: "Classic silver hoop earrings for everyday wear.",
    image: "https://images.unsplash.com/photo-1630019852942-f89202989a59?q=80&w=600&auto=format&fit=crop",
    rating: 4.3,
    stock: 18,
    material: "Sterling Silver",
    weight: "3.2g",
    purity: "92.5% Silver",
    dimensions: "25mm Hoop",
    gemstone: "None",
    metalFinish: "High Polished",
    warranty: "6 Months"
  },
  {
    name: "9K Gold Drop Earrings",
    price: 17000,
    category: "earrings",
    description: "Beautiful drop earrings crafted in 9k gold.",
    image: "https://images.unsplash.com/photo-1629224316810-9d8805b95e76?q=80&w=600&auto=format&fit=crop",
    rating: 4.6,
    stock: 10,
    material: "9K Yellow Gold",
    weight: "3.8g",
    purity: "37.5% Gold",
    dimensions: "3cm Length",
    gemstone: "None",
    metalFinish: "Polished",
    warranty: "1 Year"
  },
  {
    name: "9K Gold Bridal Earrings",
    price: 21000,
    category: "earrings",
    description: "Traditional bridal earrings made with 9k gold.",
    image: "https://images.unsplash.com/photo-1615655114865-4cc1bda5901e?w=700&auto=format&fit=crop",
    rating: 4.8,
    stock: 6,
    material: "9K White Gold",
    weight: "5.5g",
    purity: "37.5% Gold",
    dimensions: "4cm Drop",
    gemstone: "Crystal",
    metalFinish: "High Polished",
    warranty: "2 Years"
  },
  {
    name: "9K Gold Classic Ring",
    price: 15000,
    category: "ring",
    description: "Classic 9k gold ring with smooth finish.",
    image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=600&auto=format&fit=crop",
    rating: 4.6,
    stock: 13,
    material: "9K Yellow Gold",
    weight: "2.5g",
    purity: "37.5% Gold",
    dimensions: "Size N (Customizable)",
    gemstone: "None",
    metalFinish: "Polished",
    warranty: "1 Year"
  },
  {
    name: "Silver Engagement Ring",
    price: 12000,
    category: "ring",
    description: "Elegant silver engagement ring with stone.",
    image: "https://images.unsplash.com/photo-1627293509201-cd0c780043e6?q=80&w=1160&auto=format&fit=crop",
    rating: 4.7,
    stock: 7,
    material: "Sterling Silver",
    weight: "2.1g",
    purity: "92.5% Silver",
    dimensions: "Size M",
    gemstone: "Zircon",
    metalFinish: "Rhodium Plated",
    warranty: "1 Year"
  },
  {
    name: "9K Gold Diamond Ring",
    price: 42000,
    category: "ring",
    description: "Luxury ring featuring 9k gold and diamond.",
    image: "https://images.unsplash.com/photo-1512163143273-bde0e3cc7407?w=700&auto=format&fit=crop",
    rating: 4.9,
    stock: 15,
    material: "9K White Gold",
    weight: "3.4g",
    purity: "37.5% Gold",
    dimensions: "0.25ct Center Stone",
    gemstone: "Diamond",
    metalFinish: "High Polished",
    warranty: "Lifetime on Diamond"
  },
  {
    name: "9K Gold Royal Ring",
    price: 39000,
    category: "ring",
    description: "Royal style ring crafted with 9k gold.",
    image: "https://images.unsplash.com/photo-1543294001-f7cd5d7fb516?q=80&w=600&auto=format&fit=crop",
    rating: 4.8,
    stock: 5,
    material: "9K Yellow Gold",
    weight: "6.2g",
    purity: "37.5% Gold",
    dimensions: "Wide Band",
    gemstone: "Ruby (Synthetic)",
    metalFinish: "Hand-engraved",
    warranty: "2 Years"
  },
  // --- ADDITIONAL EARRINGS ---
  {
    name: "9K Gold Geometric Studs",
    price: 14500,
    category: "earrings",
    description: "Modern studs in solid 9k yellow gold.",
    image: "https://images.pexels.com/photos/28716782/pexels-photo-28716782.jpeg",
    rating: 4.5,
    stock: 12,
    material: "9K Yellow Gold",
    weight: "1.8g",
    purity: "37.5% Gold",
    dimensions: "8mm Width",
    gemstone: "None",
    metalFinish: "Brushed/Matte",
    warranty: "1 Year"
  },
  {
    name: "Gold Purple Drops",
    price: 11500,
    category: "earrings",
    description: "Sparkling Purple topaz stones set in a gold drop design.",
    image: "https://images.pexels.com/photos/3881077/pexels-photo-3881077.jpeg",
    rating: 4.8,
    stock: 9,
    material: "Sterling Silver",
    weight: "3.2g",
    purity: "92.5% Silver",
    dimensions: "2.5cm Drop",
    gemstone: "Blue Topaz (Synthetic)",
    metalFinish: "Polished",
    warranty: "1 Year"
  },
  {
    name: "9K Rose Gold Crawler Earrings",
    price: 19500,
    category: "earrings",
    description: "Elegant ear crawlers that follow the curve of the ear lobe.",
    image: "https://images.pexels.com/photos/6689398/pexels-photo-6689398.jpeg",
    rating: 4.6,
    stock: 6,
    material: "9K Rose Gold",
    weight: "2.1g",
    purity: "37.5% Gold",
    dimensions: "2cm Curve",
    gemstone: "Tiny Zircons",
    metalFinish: "High Shine",
    warranty: "1 Year"
  },
  {
    name: "Ornate Earrings with Green Gemstones",
    price: 7800,
    category: "earrings",
    description: "Minimalist long chain threaders for a contemporary look.",
    image: "https://images.pexels.com/photos/13595669/pexels-photo-13595669.jpeg",
    rating: 4.4,
    stock: 20,
    material: "Sterling Silver",
    weight: "1.2g",
    purity: "92.5% Silver",
    dimensions: "10cm total length",
    gemstone: "None",
    metalFinish: "High Polished",
    warranty: "6 Months"
  },

  // --- ADDITIONAL NECKLACES ---
  {
    name: "9K Gold Sunburst Necklace",
    price: 31000,
    category: "necklace",
    description: "Intricate sunburst pendant with a central sparkling stone.",
    image: "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?q=80&w=600&auto=format&fit=crop",
    rating: 4.7,
    stock: 14,
    material: "9K Yellow Gold",
    weight: "5.5g",
    purity: "37.5% Gold",
    dimensions: "45cm Chain",
    gemstone: "Cubic Zirconia",
    metalFinish: "Polished",
    warranty: "1 Year"
  },
  {
    name: "Close-up of a Pendant on a Chain",
    price: 15500,
    category: "necklace",
    description: "Close-up of a Pendant on a Chain in sterling silver.",
    image: "https://images.pexels.com/photos/5740933/pexels-photo-5740933.jpeg",
    rating: 4.5,
    stock: 11,
    material: "Sterling Silver",
    weight: "12.0g",
    purity: "92.5% Silver",
    dimensions: "40cm & 45cm Layers",
    gemstone: "None",
    metalFinish: "Mirror Finish",
    warranty: "1 Year"
  },
  {
    name: "9K White Gold Amethyst Pendant",
    price: 29500,
    category: "necklace",
    description: "Vibrant purple amethyst set in a white gold halo.",
    image: "https://images.pexels.com/photos/12486656/pexels-photo-12486656.jpeg",
    rating: 4.9,
    stock: 4,
    material: "9K White Gold",
    weight: "4.8g",
    purity: "37.5% Gold",
    dimensions: "42cm Chain",
    gemstone: "Amethyst",
    metalFinish: "Rhodium Plated",
    warranty: "2 Years"
  },
  {
    name: "Silver Compass Travel Necklace",
    price: 9500,
    category: "necklace",
    description: "Detailed compass rose pendant for the adventurous spirit.",
    image: "https://images.pexels.com/photos/12124596/pexels-photo-12124596.jpeg",
    rating: 4.6,
    stock: 25,
    material: "Sterling Silver",
    weight: "6.5g",
    purity: "92.5% Silver",
    dimensions: "50cm Chain",
    gemstone: "None",
    metalFinish: "Antique/Oxidized",
    warranty: "1 Year"
  },

  // --- ADDITIONAL RINGS ---
  {
    name: "Silver Ring",
    price: 12500,
    category: "ring",
    description: "Silver Ring with a Blue Crystal.",
    image: "https://images.pexels.com/photos/12081609/pexels-photo-12081609.jpeg",
    rating: 4.4,
    stock: 30,
    material: "9K Yellow Gold",
    weight: "1.9g",
    purity: "37.5% Gold",
    dimensions: "Size L-P",
    gemstone: "None",
    metalFinish: "Polished",
    warranty: "1 Year"
  },
  {
    name: "Stylish Black Ring with Hexagonal Silver Detail",
    price: 17000,
    category: "ring",
    description: "Bold rectangular black onyx stone set in heavy silver.",
    image: "https://images.pexels.com/photos/33080094/pexels-photo-33080094.jpeg",
    rating: 4.7,
    stock: 8,
    material: "Sterling Silver",
    weight: "8.5g",
    purity: "92.5% Silver",
    dimensions: "Size T (Large)",
    gemstone: "Black Onyx",
    metalFinish: "Satin Finish",
    warranty: "1 Year"
  },
  {
    name: "9K Rose Gold Eternity Band",
    price: 36000,
    category: "ring",
    description: "Full circle of sparkling stones set in warm rose gold.",
    image: "https://images.pexels.com/photos/30746009/pexels-photo-30746009.jpeg",
    rating: 4.8,
    stock: 3,
    material: "9K Rose Gold",
    weight: "3.5g",
    purity: "37.5% Gold",
    dimensions: "Size M",
    gemstone: "Cubic Zirconia",
    metalFinish: "High Polished",
    warranty: "2 Years"
  },
  {
    name: "Silver Hammered Band Ring",
    price: 4500,
    category: "ring",
    description: "Simple silver band with a hand-hammered texture.",
    image: "https://images.pexels.com/photos/32806535/pexels-photo-32806535.jpeg",
    rating: 4.2,
    stock: 45,
    material: "Sterling Silver",
    weight: "4.0g",
    purity: "92.5% Silver",
    dimensions: "Adjustable",
    gemstone: "None",
    metalFinish: "Hammered",
    warranty: "6 Months"
  }
];

module.exports = products;