const products = [
  {
    name: "9K Gold Classic Necklace",
    price: 32000,
    category: "necklace",
    description: "Elegant 9k gold necklace with minimal classic design.",
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=600&auto=format&fit=crop",
    rating: 4.6,
    stock: 18,
    material: "9K Yellow Gold",
    weight: "4.5g",
    purity: "37.5% Gold",
    dimensions: "45cm Chain",
    gemstone: "None",
    metalFinish: "Polished",
    warranty: "1 Year"
  },
  {
    name: "Silver Pearl Necklace Set",
    price: 18000,
    category: "necklace",
    description: "Beautiful silver necklace paired with pearl beads.",
    image: "https://images.pexels.com/photos/33370257/pexels-photo-33370257.jpeg",
    rating: 4.5,
    stock: 6,
    material: "Sterling Silver",
    weight: "5.8g",
    purity: "92.5% Silver",
    dimensions: "40cm + 5cm adjustment",
    gemstone: "Freshwater Pearl",
    metalFinish: "Rhodium Plated",
    warranty: "6 Months"
  },
  {
    name: "9K Gold Bridal Necklace",
    price: 45000,
    category: "necklace",
    description: "Traditional bridal necklace made with 9k gold.",
    image: "https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=700&auto=format&fit=crop",
    rating: 4.8,
    stock: 16,
    material: "9K Yellow Gold",
    weight: "14.2g",
    purity: "37.5% Gold",
    dimensions: "50cm Drop Design",
    gemstone: "Cubic Zirconia",
    metalFinish: "High Shine",
    warranty: "2 Years"
  },
  {
    name: "9K Gold Modern Necklace",
    price: 35000,
    category: "necklace",
    description: "Modern pattern necklace crafted in 9k gold.",
    image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?q=80&w=600&auto=format&fit=crop",
    rating: 4.7,
    stock: 17,
    material: "9K Rose Gold",
    weight: "6.5g",
    purity: "37.5% Gold",
    dimensions: "42cm",
    gemstone: "None",
    metalFinish: "Matte/Satin Finish",
    warranty: "1 Year"
  },

  {
    name: "9K Gold Stud Earrings",
    price: 12000,
    category: "earrings",
    description: "Simple and elegant 9k gold stud earrings.",
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=600&auto=format&fit=crop",
    rating: 4.4,
    stock: 15,
    material: "9K Yellow Gold",
    weight: "1.1g",
    purity: "37.5% Gold",
    dimensions: "6mm Diameter",
    gemstone: "None",
    metalFinish: "Polished",
    warranty: "1 Year"
  },
  {
    name: "Silver Hoop Earrings",
    price: 9000,
    category: "earrings",
    description: "Classic silver hoop earrings for everyday wear.",
    image: "https://images.unsplash.com/photo-1630019852942-f89202989a59?q=80&w=600&auto=format&fit=crop",
    rating: 4.3,
    stock: 18,
    material: "Sterling Silver",
    weight: "3.2g",
    purity: "92.5% Silver",
    dimensions: "25mm Hoop",
    gemstone: "None",
    metalFinish: "High Polished",
    warranty: "6 Months"
  },
  {
    name: "9K Gold Drop Earrings",
    price: 17000,
    category: "earrings",
    description: "Beautiful drop earrings crafted in 9k gold.",
    image: "https://images.unsplash.com/photo-1629224316810-9d8805b95e76?q=80&w=600&auto=format&fit=crop",
    rating: 4.6,
    stock: 10,
    material: "9K Yellow Gold",
    weight: "3.8g",
    purity: "37.5% Gold",
    dimensions: "3cm Length",
    gemstone: "None",
    metalFinish: "Polished",
    warranty: "1 Year"
  },
  {
    name: "9K Gold Bridal Earrings",
    price: 21000,
    category: "earrings",
    description: "Traditional bridal earrings made with 9k gold.",
    image: "https://images.unsplash.com/photo-1615655114865-4cc1bda5901e?w=700&auto=format&fit=crop",
    rating: 4.8,
    stock: 6,
    material: "9K White Gold",
    weight: "5.5g",
    purity: "37.5% Gold",
    dimensions: "4cm Drop",
    gemstone: "Crystal",
    metalFinish: "High Polished",
    warranty: "2 Years"
  },
  {
    name: "9K Gold Classic Ring",
    price: 15000,
    category: "ring",
    description: "Classic 9k gold ring with smooth finish.",
    image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=600&auto=format&fit=crop",
    rating: 4.6,
    stock: 13,
    material: "9K Yellow Gold",
    weight: "2.5g",
    purity: "37.5% Gold",
    dimensions: "Size N (Customizable)",
    gemstone: "None",
    metalFinish: "Polished",
    warranty: "1 Year"
  },
  {
    name: "Silver Engagement Ring",
    price: 12000,
    category: "ring",
    description: "Elegant silver engagement ring with stone.",
    image: "https://images.unsplash.com/photo-1627293509201-cd0c780043e6?q=80&w=1160&auto=format&fit=crop",
    rating: 4.7,
    stock: 7,
    material: "Sterling Silver",
    weight: "2.1g",
    purity: "92.5% Silver",
    dimensions: "Size M",
    gemstone: "Zircon",
    metalFinish: "Rhodium Plated",
    warranty: "1 Year"
  },
  {
    name: "9K Gold Diamond Ring",
    price: 42000,
    category: "ring",
    description: "Luxury ring featuring 9k gold and diamond.",
    image: "https://images.unsplash.com/photo-1512163143273-bde0e3cc7407?w=700&auto=format&fit=crop",
    rating: 4.9,
    stock: 15,
    material: "9K White Gold",
    weight: "3.4g",
    purity: "37.5% Gold",
    dimensions: "0.25ct Center Stone",
    gemstone: "Diamond",
    metalFinish: "High Polished",
    warranty: "Lifetime on Diamond"
  },
  {
    name: "9K Gold Royal Ring",
    price: 39000,
    category: "ring",
    description: "Royal style ring crafted with 9k gold.",
    image: "https://images.unsplash.com/photo-1543294001-f7cd5d7fb516?q=80&w=600&auto=format&fit=crop",
    rating: 4.8,
    stock: 5,
    material: "9K Yellow Gold",
    weight: "6.2g",
    purity: "37.5% Gold",
    dimensions: "Wide Band",
    gemstone: "Ruby (Synthetic)",
    metalFinish: "Hand-engraved",
    warranty: "2 Years"
  }
];

module.exports = products;